In [3]:
import numpy as np


In [4]:
a=[10,11,12,13]

In [5]:
type(a)

list

In [8]:
x=np.array(a)
print(x)
type(x)


[10 11 12 13]


numpy.ndarray

In [12]:
a = [1,2,3,4]
b = [10,20,30,40]
x = np.array([a,b])
print(x)

[[ 1  2  3  4]
 [10 20 30 40]]


In [19]:
a = [1,2,3,4]
b = [10,20,30,40]
x = np.array([a,b])
print(x)

[[ 1  2  3  4]
 [10 20 30 40]]


In [20]:
x= np.array([1,2,3,4],dtype = np.float32)
print(x)

[1. 2. 3. 4.]


In [22]:
x =np.zeros((2,3))
print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


In [23]:
x = np.zeros((4,4))
print(x)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [24]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [25]:
np.ones(5, dtype = np.int32)

array([1, 1, 1, 1, 1], dtype=int32)

In [26]:
x = np.random.rand(2,5)
print(x)

[[0.16605981 0.3256786  0.02105874 0.4634269  0.547562  ]
 [0.22352032 0.07157902 0.99308158 0.64435148 0.44297621]]


In [31]:
np.random.randint(1,20, size = (3,3))

array([[ 6, 12,  2],
       [ 2,  3,  1],
       [19, 19, 14]], dtype=int32)

In [35]:
np.random.choice([2,3,4,7,8,10])

np.int64(2)

In [37]:
np.full((3,4),10)

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [38]:
np.ones((3,3))*10

array([[10., 10., 10.],
       [10., 10., 10.],
       [10., 10., 10.]])

In [39]:
x = np.eye(4, k = -1)
print(x)

[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [40]:
np.arange(5,11)

array([ 5,  6,  7,  8,  9, 10])

In [41]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [42]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [43]:
a = [10,20,30,40,50]
x = np.array(a)
print(x)

[10 20 30 40 50]


In [44]:
x.ndim

1

In [47]:
b = [1,2,3,4,5]
y = np.array([a,b])
print(y)
y.ndim
y.shape
y.size

[[10 20 30 40 50]
 [ 1  2  3  4  5]]


10

In [48]:
a = np.array([3,6,9,12])
print(a)
np.reshape(a, (2,2))
a.reshape(2,2)



[ 3  6  9 12]


array([[ 3,  6],
       [ 9, 12]])

In [54]:
x = np.arange(1,16)
x


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [50]:
x.size

15

In [51]:
x.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [55]:
x = np.arange(1,16)
print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [56]:
y = x.reshape(3,5)
print(y)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [57]:
z = np.transpose(y)
print(z)

[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


In [58]:
y.transpose()

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

In [59]:
a = np.arange(1,10)
print(a)

[1 2 3 4 5 6 7 8 9]


In [60]:
a[2:6]


array([3, 4, 5, 6])

In [61]:
x = np.arange(1,10).reshape(3,3)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [63]:
x[1,2]

np.int64(6)

In [64]:
x[1:3,1:3]

array([[5, 6],
       [8, 9]])

In [73]:
a = np.arange(1,6)
b = np.arange(6,11)
print(a)
print(b)


[1 2 3 4 5]
[ 6  7  8  9 10]


In [72]:
x = np.vstack((a,b))
print("X:",x)

X: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [75]:
x = np.hstack((a,b))
print(x)

[ 1  2  3  4  5  6  7  8  9 10]


In [76]:
a = np.arange(1,10).reshape(3,3)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [77]:
b = np.arange(10,19).reshape(3,3)
print(b)


[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [78]:
np.concatenate((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [79]:
np.concatenate((a,b), axis = 1)

array([[ 1,  2,  3, 10, 11, 12],
       [ 4,  5,  6, 13, 14, 15],
       [ 7,  8,  9, 16, 17, 18]])